/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCredentialsRouteImport } from './routes/_authenticated/credentials'
import { Route as AuthenticatedWorkflowsIdRouteImport } from './routes/_authenticated/workflows.$id'
import { Route as ApiPublicWhTokenRouteImport } from './routes/api/public/wh.$token'
import { Route as ApiPublicSchedulerTickRouteImport } from './routes/api/public/scheduler.tick'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCredentialsRoute =
  AuthenticatedCredentialsRouteImport.update({
    id: '/credentials',
    path: '/credentials',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkflowsIdRoute =
  AuthenticatedWorkflowsIdRouteImport.update({
    id: '/workflows/$id',
    path: '/workflows/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWhTokenRoute = ApiPublicWhTokenRouteImport.update({
  id: '/api/public/wh/$token',
  path: '/api/public/wh/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSchedulerTickRoute = ApiPublicSchedulerTickRouteImport.update({
  id: '/api/public/scheduler/tick',
  path: '/api/public/scheduler/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/credentials': typeof AuthenticatedCredentialsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/api/public/scheduler/tick': typeof ApiPublicSchedulerTickRoute
  '/api/public/wh/$token': typeof ApiPublicWhTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/credentials': typeof AuthenticatedCredentialsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/api/public/scheduler/tick': typeof ApiPublicSchedulerTickRoute
  '/api/public/wh/$token': typeof ApiPublicWhTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/credentials': typeof AuthenticatedCredentialsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/workflows/$id': typeof AuthenticatedWorkflowsIdRoute
  '/api/public/scheduler/tick': typeof ApiPublicSchedulerTickRoute
  '/api/public/wh/$token': typeof ApiPublicWhTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/credentials'
    | '/dashboard'
    | '/workflows/$id'
    | '/api/public/scheduler/tick'
    | '/api/public/wh/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/credentials'
    | '/dashboard'
    | '/workflows/$id'
    | '/api/public/scheduler/tick'
    | '/api/public/wh/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_authenticated/credentials'
    | '/_authenticated/dashboard'
    | '/_authenticated/workflows/$id'
    | '/api/public/scheduler/tick'
    | '/api/public/wh/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiPublicSchedulerTickRoute: typeof ApiPublicSchedulerTickRoute
  ApiPublicWhTokenRoute: typeof ApiPublicWhTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/credentials': {
      id: '/_authenticated/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof AuthenticatedCredentialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflows/$id': {
      id: '/_authenticated/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof AuthenticatedWorkflowsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/wh/$token': {
      id: '/api/public/wh/$token'
      path: '/api/public/wh/$token'
      fullPath: '/api/public/wh/$token'
      preLoaderRoute: typeof ApiPublicWhTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scheduler/tick': {
      id: '/api/public/scheduler/tick'
      path: '/api/public/scheduler/tick'
      fullPath: '/api/public/scheduler/tick'
      preLoaderRoute: typeof ApiPublicSchedulerTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCredentialsRoute: typeof AuthenticatedCredentialsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedWorkflowsIdRoute: typeof AuthenticatedWorkflowsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCredentialsRoute: AuthenticatedCredentialsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedWorkflowsIdRoute: AuthenticatedWorkflowsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiPublicSchedulerTickRoute: ApiPublicSchedulerTickRoute,
  ApiPublicWhTokenRoute: ApiPublicWhTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
